[tool.poetry]
name = "zemfrog-test"
version = "1.0.1"
description = "Zemfrog unit testing tools"
authors = ["aprilahijriyan <hijriyan23@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.7,<4.0"
zemfrog = "^4.0.5"
pytest = "^6.2.2"
ipython = {git = "https://github.com/ipython/ipython"}

[tool.poetry.dev-dependencies]
pre-commit = "^2.11.1"

[tool.poetry.plugins]

pytest11 = {zemfrog_test = "zemfrog_test.fixtures"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
